services:
  airs:
    build:
      context: ./airs
      args:
        - AIRS_BASE_IMAGE=${AIRS_BASE_IMAGE}
    image: ${AIRS_TAG}
    container_name: airs
    ports:
      - "8080:8080"
    volumes:
      - /home/josh/work:/work
      - /home/josh/code-server/home:/home/josh
      - /home/josh/code-server/data:/home/josh/.local/share/code-server
      - /home/josh/code-server/extensions:/home/josh/.local/share/code-server/extensions
      - /home/josh/.ssh:/home/josh/.ssh:ro
    runtime: nvidia
    environment:
      NVIDIA_VISIBLE_DEVICES: all
      CS_USER: josh
      CS_UID: 1000
      CS_GID: 1000