services:
  airs:
    build:
      context: ./airs
      args:
        - AIRS_BASE_IMAGE=${AIRS_BASE_IMAGE}
    image: ${AIRS_TAG}
    container_name: airs
    ports:
      - "8080:8080"
    command: ["code-server", "--bind-addr", "0.0.0.0:8080", "--auth", "none"]